// Concepts tracked for mastery, grouped by lecture.
export const LECTURES = [
  { n: 7, id: 'l07', title: 'Introduction to data structures', short: 'Intro', file: 'Lec07_Intro_Data_Structures.pdf', pages: 4 },
  { n: 8, id: 'l08', title: 'Singly linked lists — part 1', short: 'SLL 1', file: 'Lec08_Single_Linked_List_01.pdf', pages: 7 },
  { n: 9, id: 'l09', title: 'Singly linked lists — part 2', short: 'SLL 2', file: 'Lec09_Single_Linked_List_02.pdf', pages: 5 },
  { n: 10, id: 'l10', title: 'Doubly linked lists', short: 'DLL', file: 'Lec10_Double_Linked_List.pdf', pages: 7 },
  { n: 11, id: 'l11', title: 'Circular singly linked lists', short: 'Circular', file: 'Lec11_Circular_Single_Linked_List.pdf', pages: 4 },
  { n: 12, id: 'l12', title: 'Stacks and queues', short: 'Stack/Queue', file: 'Lec12_Stack_and_Queue.pdf', pages: 6 },
  { n: 13, id: 'l13', title: 'Trees and graphs', short: 'Trees/Graphs', file: 'Lec13_Trees_and_Graphs.pdf', pages: 6 },
  { n: 14, id: 'l14', title: 'Traversing trees and graphs', short: 'Traversals', file: 'Lec14_Traversing_Trees_Graphs.pdf', pages: 4 },
];

export const CONCEPTS = [
  { id: 'l07.arrays-vs-lists', lecture: 7, name: 'Arrays vs linked lists: operation costs' },
  { id: 'l07.linear-nonlinear', lecture: 7, name: 'Linear vs non-linear structures' },
  { id: 'l07.memory-layout', lecture: 7, name: 'Contiguous memory and storage location' },
  { id: 'l07.pointers-alloc', lecture: 7, name: 'Pointers, malloc() and free()' },
  { id: 'l07.tradeoffs', lecture: 7, name: 'Choosing a structure by its tradeoffs' },
  { id: 'l08.node-anatomy', lecture: 8, name: 'Node fields: value vs address' },
  { id: 'l08.traversal-pointer', lecture: 8, name: 'start, temp and walking the list' },
  { id: 'l08.insert-beg', lecture: 8, name: 'Insert at the beginning' },
  { id: 'l08.insert-mid', lecture: 8, name: 'Insert in the middle' },
  { id: 'l08.insert-end', lecture: 8, name: 'Insert at the end' },
  { id: 'cx.list-costs', lecture: 8, name: 'Cost: finding a position vs changing links' },
  { id: 'l09.delete-beg', lecture: 9, name: 'Delete at the beginning' },
  { id: 'l09.delete-mid', lecture: 9, name: 'Delete at an intermediate position' },
  { id: 'l09.delete-end', lecture: 9, name: 'Delete at the end (incl. one node)' },
  { id: 'l09.traverse', lecture: 9, name: 'Traversal and output' },
  { id: 'l09.preserve-access', lecture: 9, name: 'Preserving access & freeing safely' },
  { id: 'cx.tail-pointer', lecture: 9, name: 'Cost: what a tail pointer does (not) fix' },
  { id: 'l10.dll-links', lecture: 10, name: 'left/right links agree' },
  { id: 'l10.dll-insert', lecture: 10, name: 'Doubly linked insertion' },
  { id: 'l10.dll-delete', lecture: 10, name: 'Doubly linked deletion' },
  { id: 'l10.dll-traverse', lecture: 10, name: 'Forward and backward traversal' },
  { id: 'l10.countnode', lecture: 10, name: 'Recursive countnode' },
  { id: 'l11.circular-links', lecture: 11, name: 'Circular links and one lap' },
  { id: 'l11.csll-traverse', lecture: 11, name: 'Circular traversal termination' },
  { id: 'l11.csll-insert', lecture: 11, name: 'Circular insertion' },
  { id: 'l11.csll-delete', lecture: 11, name: 'Circular deletion' },
  { id: 'l11.csll-edge', lecture: 11, name: 'Empty and one-node circles' },
  { id: 'cx.circular-costs', lecture: 11, name: 'Cost: finding the last node in a circle' },
  { id: 'l12.lifo-fifo', lecture: 12, name: 'LIFO vs FIFO' },
  { id: 'l12.array-stack', lecture: 12, name: 'Array stack: top, overflow, underflow' },
  { id: 'l12.linked-stack', lecture: 12, name: 'Linked stack' },
  { id: 'l12.array-queue', lecture: 12, name: 'Array queue: F, R, full/empty' },
  { id: 'l12.linked-queue', lecture: 12, name: 'Linked queue: front and rear' },
  { id: 'cx.stack-ends', lecture: 12, name: 'Cost: stack at the head vs at the tail' },
  { id: 'l13.tree-terms', lecture: 13, name: 'Tree terminology' },
  { id: 'l13.tree-measures', lecture: 13, name: 'Levels, height, depth, formulas' },
  { id: 'l13.tree-classify', lecture: 13, name: 'Strict / full(perfect) / complete' },
  { id: 'l13.tree-repr', lecture: 13, name: 'Array vs linked tree representation' },
  { id: 'l13.graph-repr', lecture: 13, name: 'Adjacency matrix and list' },
  { id: 'l14.tree-traversal', lecture: 14, name: 'Preorder, inorder, postorder' },
  { id: 'l14.dfs', lecture: 14, name: 'Depth-first search' },
  { id: 'l14.bfs', lecture: 14, name: 'Breadth-first search' },
  { id: 'l14.components', lecture: 14, name: 'Reachable component vs whole graph' },
  { id: 'l14.traversal-cost', lecture: 14, name: 'Traversal cost: list vs matrix' },
];

export const CONCEPT_BY_ID = Object.fromEntries(CONCEPTS.map((c) => [c.id, c]));

export const MISTAKE_LABELS = {
  'lost-access': 'Overwrote the only pointer to the rest of the list',
  'free-before-unlink': 'Freed a node that was still linked',
  dangling: 'Left a pointer to freed memory (dangling)',
  'back-link': 'Forgot or mis-set a backward (left) link',
  'circle-not-closed': 'Did not keep the circular list closed',
  'circular-null': 'Waited for NULL in a circular list',
  'circular-lap': 'Went around a circle more than once',
  'tail-rear': 'tail/rear not pointing at the last node',
  'value-vs-address': 'Confused a node’s value with its address',
  'off-by-one': 'Off-by-one counting',
  'pointer-walk': 'Mis-tracked a walking pointer',
  'loop-condition': 'Wrong loop condition',
  'infinite-loop': 'Loop never terminates',
  'null-deref': 'Dereferenced NULL or freed memory',
  'lifo-fifo': 'Mixed up LIFO and FIFO',
  'top-convention': 'Misread what top / rear means',
  'linear-queue-full': 'Linear array queue “full” with free slots',
  'queue-indices': 'Mis-tracked F and R',
  overflow: 'Overflow / underflow conditions',
  'height-convention': 'Edges vs nodes convention for height/depth',
  'full-vs-perfect': '“Full” vs “perfect” vs strictly binary naming',
  complete: 'Complete-tree definition',
  'array-base': '0-based vs 1-based array positions',
  'matrix-symmetry': 'Undirected edge entered only once in the matrix',
  'matrix-direction': 'Direction of edges in a matrix/list',
  adjlist: 'Adjacency list contents',
  'order-confusion': 'Mixed up preorder / inorder / postorder',
  'bfs-dfs-confusion': 'Mixed up BFS and DFS',
  'bfs-weight': 'Assumed BFS minimises total weight',
  'list-vs-matrix': 'List vs matrix traversal cost',
  relation: 'Tree relationship terms',
  'position-range': 'Valid position ranges',
  'shift-count': 'Counting array shifts',
  'memory-bug': 'Leak / dangling / double free',
  'storage-location': 'Stack vs heap vs static storage',
  sizeof: 'sizeof in malloc',
  'recursion-base': 'Forgot the base-case call',
  singleton: 'One-node edge case',
  syntax: 'Code could not be read',
  leak: 'Memory leak',
  'wrong-result': 'Wrong final structure',
};
